version: '3.8'

services:
  app:
    build: .
    container_name: bayes-react-app
    ports:
      - "3000:80"
    restart: always
    networks:
      - web_gateway
      - default

networks:
  web_gateway:
    external: true
